<?php
namespace LaunchDarkly;

/**
 * A snapshot of the state of all feature flags with regard to a specific user.
 *
 * This is generated by calling {@link \LaunchDarkly\LDClient::allFlagsState()}.
 *
 * Serializing this object to JSON using json_encode(), or the jsonSerialize() method, will produce the
 * appropriate data structure for bootstrapping the LaunchDarkly JavaScript client. See the SDK
 * reference guide on ["Bootstrapping"](https://docs.launchdarkly.com/docs/js-sdk-reference#section-bootstrapping).
 */
class FeatureFlagsState implements \JsonSerializable
{
    /** @var bool */
    protected $_valid = false;

    /** @var array */
    protected $_flagValues;

    /** @var array */
    protected $_flagMetadata;

    /**
     * @ignore
     */
    public function __construct(bool $valid, array $flagValues = array(), array $flagMetadata = array())
    {
        $this->_valid = $valid;
        $this->_flagValues = array();
        $this->_flagMetadata = array();
    }

    /**
     * Used internally to build the state map.
     *
     * @ignore
     * 
     * @return void
     */
    public function addFlag(
        FeatureFlag $flag,
        EvaluationDetail $detail,
        bool $withReason = false,
        bool $detailsOnlyIfTracked = false): void
    {
        $this->_flagValues[$flag->getKey()] = $detail->getValue();
        $meta = array();
        if (!$detailsOnlyIfTracked || $flag->isTrackEvents() || $flag->getDebugEventsUntilDate()) {
            $meta['version'] = $flag->getVersion();
            if ($withReason) {
                $meta['reason'] = $detail->getReason();
            }
        }
        if (!is_null($detail->getVariationIndex())) {
            $meta['variation'] = $detail->getVariationIndex();
        }
        if ($flag->isTrackEvents()) {
            $meta['trackEvents'] = true;
        }
        if ($flag->getDebugEventsUntilDate()) {
            $meta['debugEventsUntilDate'] = $flag->getDebugEventsUntilDate();
        }
        $this->_flagMetadata[$flag->getKey()] = $meta;
    }

    /**
     * Returns true if this object contains a valid snapshot of feature flag state, or false if the
     * state could not be computed (for instance, because the client was offline or there was no user).
     * @return bool true if the state is valid
     */
    public function isValid(): bool
    {
        return $this->_valid;
    }

    /**
     * Returns the value of an individual feature flag at the time the state was recorded.
     * @param string $key the feature flag key
     * @return mixed the flag's value; null if the flag returned the default value, or if there was no such flag
     */
    public function getFlagValue(string $key)
    {
        return isset($this->_flagValues[$key]) ? $this->_flagValues[$key] : null;
    }

    /**
     * Returns the evaluation reason for an individual feature flag (as returned by LDClient.variationDetail())
     * at the time the state was recorded.
     * @param string $key the feature flag key
     * @return EvaluationReason|null the evaluation reason; null if reasons were not recorded, or if there
     * was no such flag
     */
    public function getFlagReason(string $key): ?EvaluationReason
    {
        if (isset($this->_flagMetadata[$key])) {
            $meta = $this->_flagMetadata[$key];
            return isset($meta['reason']) ? $meta['reason'] : null;
        }
        return null;
    }

    /**
     * Returns an associative array of flag keys to flag values. If a flag would have evaluated to the default
     * value, its value will be null.
     * <p>
     * Do not use this method if you are passing data to the front end to "bootstrap" the JavaScript client.
     * Instead, use jsonSerialize().
     * @return array an associative array of flag keys to JSON values
     */
    public function toValuesMap(): array
    {
        return $this->_flagValues;
    }

    /**
     * Returns a JSON representation of the entire state map (as an associative array), in the format used
     * by the LaunchDarkly JavaScript SDK. Use this method if you are passing data to the front end in
     * order to "bootstrap" the JavaScript client.
     * <p>
     * Note that calling json_encode() on a FeatureFlagsState object will automatically use the
     * jsonSerialize() method.
     * @return array an associative array suitable for passing as a JSON object
     */
    public function jsonSerialize(): array
    {
        $ret = array_replace([], $this->_flagValues);
        $metaMap = array();
        foreach ($this->_flagMetadata as $key => $meta) {
            $meta = array_replace([], $meta);
            if (isset($meta['reason'])) {
                $meta['reason'] = $meta['reason']->jsonSerialize();
            }
            $metaMap[$key] = $meta;
        }
        $ret['$flagsState'] = $metaMap;
        $ret['$valid'] = $this->_valid;
        return $ret;
    }
}
