name: CI Workflow
description: 'Shared CI workflow.'
inputs:
  php-version:
    description: 'Which version of PHP should we setup?'
    required: false
    default: 8.1
  use-lowest-dependencies:
    description: 'Should we prefer the lowest dependency version?'
    type: boolean
    required: false
    default: false
  token:
    description: 'Token used to prevent composer rate limiting'
    required: true

runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@e6f75134d35752277f093989e72e140eaa222f35
      with:
        php-version: ${{ inputs.php-version }}
        extensions: xdebug
        tools: phpdoc:3.3.1
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Install dependencies
      shell: bash
      run: composer install --no-progress

    - name: Downgrade to lowest versions
      if: ${{ inputs.use-lowest-dependencies }}
      shell: bash
      run: composer update --prefer-lowest --prefer-stable

    - name: Run unit tests
      shell: bash
      run: make test

    - name: Run lint checks
      shell: bash
      run: make lint

    - name: Build contract tests
      shell: bash
      run: make build-contract-tests

    - name: Start contract test service
      shell: bash
      run: make start-contract-test-service-bg

    - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.0.2
      with:
        test_service_port: 8000
        token: ${{ inputs.token }}
        extra_params: "-skip 'evaluation/parameterized/attribute references/array index is not supported'"
